server:
  port: 8081
  servlet:
    context-path: /student
#    数据库连接
spring:
  datasource:
    name: mybatis
    username: root
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: gkjy383910
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false

logging:
  level:
    com.dormitory.mapper: debug


file:
  upload-path: E:\头像资源


